name: LibraryBuild
on: [push, pull_request]
jobs:
  build:
    name: Test compiling examples for M5stack-Core2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@v3
      with:
        arduino-board-fqbn:  esp32:esp32:m5stack-core2:FlashFreq=80
        platform-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json
        required-libraries: FastLED,Adafruit_NeoPixel,Adafruit_SGP30,Adafruit_Sensor,Adafruit_BMP280,Adafruit_MCP4725,Adafruit_TCS34725,Adafruit_PWMServoDriver
        
